apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-add-tasks-api
  template:
    metadata:
      labels:
        app: todo-add-tasks-api
    spec:
      containers:
      - name: todo-add-tasks-api
        image: azureuserkey.azurecr.io/addtasktodoimage:v10
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devopsinsider.database.windows.net,1433;Database=azureuserdatabase;Uid=azureuser;Pwd=Devops@insider;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
