apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-tasks-api-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devopsinsider.database.windows.net,1433;Database=azureuserdatabase;Uid=azureuser;Pwd=Devops@insider;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: azureuserkey.azurecr.io/addtasktodoimage:v3
        ports:
        - containerPort: 8000
