# apiVersion: v1
# kind: Service
# metadata:
#   name: todo-add-tasks-api-ingress
# spec:
#   type: ClusterIP
#   selector:
#     app: add-task
#   ports:
#   - port: 80
#     targetPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: todo-add-tasks-api
spec:
  type: LoadBalancer
  selector:
    app: todo-add-tasks-api
  ports:
    - port: 80
      targetPort: 8000
