apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-tasks-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: get-tasks.6weathers.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: get-tasks
            port:
              number: 80

